### ISSUE TITLE
ClientApp renders twice when following a react-router link

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1919]
**Describe the bug**
The ClientApp is rendering multiple times when following a react router link, it appears to render with the current payload then follow the link and render again with the new payload. 

**To Reproduce**

1. Checkout [re-rendering](https://github.com/bbc/simorgh/pull/1920)
2. `npm run dev`
3. Visit http://localhost:7080/news/articles/c0g992jmmkko and click the link to the next optimo article `placed on the tomb of the unknown warrior`
4. Open console and see errors

**Expected behavior**
The ClientApp should only trigger one load of the App -> Article -> ArticleMain. Please add a test to `App.test.jsx` which checks we render the App once and once only. 

**Screenshots**

**Additional context**
This is causing issues where the ATI beacon is fired twice on a client page transition, the first beacon being the original page and the second beacon being the page being routed to. This makes me believe the ClientApp is re-rendering before following the react-router-link.

**Comment by pjlee11** [comment]
Blocking https://github.com/bbc/simorgh/pull/1651

**Comment by dr3** [comment]
I might be misunderstanding, but as far as I can see it does

```
- USER NAVIGATE
1) in app container
   state in app {data: {…}, service: "news", id: "c0g992jmmkko", isAmp: false, loading: false, …}

2) in article main container

3) in app container
   state in app {data: null, service: "news", id: "c6v11qzyv8po", isAmp: false, loading: true, …}

4) in app container
state in app {data: {…}, service: "news", id: "c6v11qzyv8po", isAmp: false, loading: false, …}

5) in article main container
```
```
1) renders because prop changes (location)(from upstream router state)
2) renders because its downstream of app (number 1)(rerenders the same because useEffect hasn't run yet to change data)
3) renders because the useEffect hook runs and changes state (loading true + data stuff)
4) renders because the state changes (loading false + data stuff)
5) renders because its downstream of app & loading is false (number 4)
```
Im not sure how we can avoid any of these
(I may be missing something so apologies)

**Comment by sareh** [comment]
Drew, that is a good summary of the steps. 
We should prevent the render in step 2 - since on a click from article A to article B, the application renders the article A again prior to rendering article B. 

When location is changed, we firstly set the state to the initial values `loading false`, etc [file here](https://github.com/bbc/simorgh/blob/548e9f61140283073ed0340eee63633ecb732645/src/app/containers/App/App.jsx#L14) prior to the useEffect hook to update the state. 

We should change this to not reset the state to the initial values each time App is rendered.

**Comment by dr3** [comment]
>When location is changed, we firstly set the state to the initial values loading false, etc [file here](https://github.com/bbc/simorgh/blob/548e9f61140283073ed0340eee63633ecb732645/src/app/containers/App/App.jsx#L14) prior to the useEffect hook to update the state.

Is that the case? Its my understanding that useState, outside a useEffect, only runs once, on mount. So [this useState](https://github.com/bbc/simorgh/blob/548e9f61140283073ed0340eee63633ecb732645/src/app/containers/App/App.jsx#L14) doesnt run when you update location

Edit: Just did an example which I think confirms it only runs once, if you add a random key, like `foobar: barfoo` to [this useState](https://github.com/bbc/simorgh/blob/548e9f61140283073ed0340eee63633ecb732645/src/app/containers/App/App.jsx#L14), it only appears in the state console logs until step 3, when the useEffect hook runs and changes state. After that, the foobar key never returns, implying this [this useState](https://github.com/bbc/simorgh/blob/548e9f61140283073ed0340eee63633ecb732645/src/app/containers/App/App.jsx#L14) doesnt rerun on location updates, as foobar is never re-added to state

**Comment by sareh** [comment]
@dr3 I see that being added to state on location updates. 
I've just pushed debug fields to the stateStates on the example branch mentioned: https://github.com/bbc/simorgh/pull/1920/files#diff-075d3e454c8d5028eecfaf8c11b80de1R18 


This is my output when clicking through to a new article. The initial setState is run `debug: 'first'`.

<img width="601" alt="Screen Shot of console" src="https://user-images.githubusercontent.com/3028997/59413175-f2e26b80-8db6-11e9-90a0-d33cc892bccd.png">

**Comment by jamesbhobbs** [comment]
I've spent quite a bit of time reading through App.jsx, it's very difficult to summarise. But I will try...

Responding to route/location change
- There is an initial page render
then in App.jsx...
- Use effect triggers another render then sets data to null then requests data
- setState is then used which rerenders
^ one of these is clearly avoidable as a render.

Supplementary issues with App.jsx:
1. It has isAmp logic on server and clientside, which is redundant on the clientside
2. As stated above it sets data to null before then setting it to fetched data, I don't believe this is necessary, it should I think only be set in the case of an error.
3. This
`  useEffect(() => {
    if (isInitialMount.current) {
      isInitialMount.current = false;
    }`
is kind of what we want but has a not good consequence, that even if the data endpoints are working fine the SSR page will be used and not rerender based on updated data from the data endpoint because on initial render it's never requested. This reduces our resiliency/increase our stale content in the event of falling back to persistent cache.
4. loading and withLoading: firstly it's got not timer before it starts, this is silly and causes a flash for users and secondly why are we doing this at all when the normal handling of this in react is a component render transition using something like https://github.com/reactjs/react-transition-group (not suggesting using this, just giving a popular example).
5. By forcing rerender via useEffect all child components of App are rerendered irrespective of props/state change, we can selectively use React.memo to avoid this, but should profile carefully if the extra shallow compare is worth the cost vs what could be a cheap rerender.
6. We should also consider useLayoutEffect while we have heavy rerendering inside this hook, this avoids repaints but can have lower perceived performance and worse first paint times as it blocks render on DOM completion.

**Comment by oluoluoxenfree** [comment]
@pjlee11 is this still replicable on the branch that is linked? I only get one load

**Comment by chris-hinds** [comment]
@dr3 @pjlee11 do you think this still needs to be worked on right now?

**Comment by dr3** [comment]
@hindsc52, personally no. It should still happen, but its a tiny tiny issue that imo isnt an issue

**Comment by andrewscfc** [comment]
Blocked until https://github.com/bbc/simorgh/issues/1302 is completed, @itimirichard has a PR for this issue: https://github.com/bbc/simorgh/pull/4455
