### ISSUE TITLE
Cookies should set `SameSite=None` & Secure

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4227]
**Is your feature request related to a problem? Please describe.**
Chrome is changing their policy on setting cookies.

The below is a warning message we see in the chrome console, future releases of chrome will stop delivering/settings cookies.

```
A cookie associated with a cross-site resource at http://bbc.co.uk/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

![image](https://user-images.githubusercontent.com/14273378/66814797-1a953c00-ef2f-11e9-9352-f25204a0e6b1.png)

Chrome Policies:
https://www.chromestatus.com/feature/5088147346030592
https://www.chromestatus.com/feature/5633521622188032

**Describe the solution you'd like**
When setting a cookie on a cross site domain i.e. bbc.com > bbc.co.uk ensure that we add the `SameSite=None` and `Secure` attributes.

**Testing notes**

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
I've noticed this in the Chrome notes:
>******NOTE: There is currently a bug affecting Mac OSX and iOS which causes SameSite=None cookies to be inadvertently treated as SameSite=Strict and therefore not sent with cross-site requests. (See https://bugs.webkit.org/show_bug.cgi?id=198181) Until this is fixed, SameSite=None may not work properly on Safari.******

We should check that this change doesn't break cookies on Safari (iOS and Mac). 
e.g.  noting this: https://bugs.webkit.org/show_bug.cgi?id=198181 
>But I think it's wise for you to take into consideration that we may never see support for SameSite=None on iOS 12 (and back).

cc @hindsc52 & @thekp. Tl;dr, the addition of #4391 may make cookies not work for Safari.

**Comment by chris-hinds** [comment]
> I've noticed this in the Chrome notes:
> 
> > ******NOTE: There is currently a bug affecting Mac OSX and iOS which causes SameSite=None cookies to be inadvertently treated as SameSite=Strict and therefore not sent with cross-site requests. (See https://bugs.webkit.org/show_bug.cgi?id=198181) Until this is fixed, SameSite=None may not work properly on Safari.******
> 
> We should check that this change doesn't break cookies on Safari (iOS and Mac).
> e.g. noting this: https://bugs.webkit.org/show_bug.cgi?id=198181
> 
> > But I think it's wise for you to take into consideration that we may never see support for SameSite=None on iOS 12 (and back).
> 
> cc @hindsc52 & @thekp. Tl;dr, the addition of #4391 may make cookies not work for Safari.

😱 

I agree re the testing on Safrai for IOS and MacOS.

>But I think it's wise for you to take into consideration that we may never see support for SameSite=None on iOS 12 (and back).

This is a concern...

**Comment by thekp** [comment]
> When the user is on your site, then the cookie will be sent with the request as expected. However when following a link into your site, say from another site or via an email from a friend, on that initial request the cookie will not be sent.
(source https://web.dev/samesite-cookies-explained)

From what I understand, we definitely do want this, as we get a lot of traffic through links from other sites. 🙃 

I'll try sitting down with a tester to see the behaviour of my changes: #4391

**Comment by thekp** [comment]
From some discussions on slack.

I have contacted the orbit team, asking if they are going to address this issue. In the mean time, I will be putting this issue on **blocked**, whilst we wait for Orbit to also address the issue.

**Note** the work for this issue has been done and the PR is temporary closed: https://github.com/bbc/simorgh/pull/4391

I also received clarification from Mozilla about their `Unset` value for `sameSite`, it is the same as `None` 
![image](https://user-images.githubusercontent.com/30599794/68308389-b59fb280-00a4-11ea-8f04-89e10868f448.png)

Regarding the safari bug mentioned on Chrome's status post, the link provided says that the issue has been resolved and fixed: https://bugs.webkit.org/show_bug.cgi?id=198181
But when we tested it locally, the sameSite value was being set to `-` which could be the same as `None` (unconfirmed).

**Comment by thekp** [comment]
Another note: Chrome is scheduled to release their change for the sameSite default on Feb 4th
https://www.chromestatus.com/features/schedule
![image](https://user-images.githubusercontent.com/30599794/68308687-3363be00-00a5-11ea-99e6-1c518880f294.png)

**Comment by jamesdonoh** [comment]
Following discussion with Khoa and with Orbit team
- I'n not sure `None` is the correct value here
- We should ensure consistency with how Orbit sets these cookies
- Do we actually need to do this?

It would be useful to get a list of exactly which cookie/domain combinations across .co.uk/.com produce console warnings on Simorgh pages and then analyse these in terms of a) which we actually control b) which require consistency with other implementations (e.g. `ckns_privacy`) c) what the impact of us not taking any action is

**Comment by sareh** [comment]
When visiting a page (https://www.bbc.com/afaanoromoo) in Chrome (in an incognito tab) I cannot replicate this issue. Can this ticket be closed?

**Comment by chris-hinds** [comment]
Im still seeing the same warning 
![image](https://user-images.githubusercontent.com/14273378/80964994-b7ef8900-8e09-11ea-8d07-85c831b43261.png)

**Comment by chris-hinds** [comment]
Actually I am not seeing the issue when viewing in incognito mode, so might be a plugin issue on my end

**Comment by sareh** [comment]
@hindsc52 Just to be sure, I created a new Chrome profile that didn't have any plugins or cookies set and visited https://www.bbc.com/afaanoromoo in a standard tab.
I didn't see any warnings in the console.

**Comment by thekp** [comment]
> so might be a plugin issue on my end

I think it is the chrome logger plugin, that might be console logging this for us

**Comment by thekp** [comment]
Orbit team have resolved this issue for the non-simorgh pages. This can be seen by inspecting the console here: https://www.bbc.co.uk/news, accepting the cookies then inspecting application > storage > cookies. I will apply the same cookie attributes for the cookies being set in the simorgh consent banner.

![image](https://user-images.githubusercontent.com/30599794/81065621-b8eced00-8ed3-11ea-9c1c-6863841c724e.png)

**Comment by thekp** [comment]
From what I understand about sameSite='None' is that the cookie request will be sent when a user arrives at a page from a 3rd party source (another site). Whereas the other attribute values(Lax and Strict) do not. I am not confident in my understanding of this cookie attribute so I would appreciate it if the next developer to investigate this issue would confirm the effects of the `sameSite=None` attribute

From the docs below, Google has reverted the changes to the sameSite default attribute to LAX. I'm going to move this issue back into ready for dev because it is not the highest priority anymore (https://www.chromium.org/updates/same-site).

I have a PR: https://github.com/bbc/simorgh/pull/6423 that adds the attribute sameSite and secured but it was failing on our CI: https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/simorgh/detail/UpdateCookieAttribute/14/pipeline/28


Useful google docs regarding sameSite: https://www.chromium.org/updates/same-site
Some FAQ about sameSite attribute can be found here: https://www.chromium.org/updates/same-site/faq

**Comment by thekp** [comment]
I've re-opened this issue because we had to revert the merged PR that completed the work for this: 
original PR: https://github.com/bbc/simorgh/pull/6423
reverted PR: https://github.com/bbc/simorgh/pull/7065

**Manual Testing** ✅ Notes from the test can be found here: https://github.com/bbc/simorgh/pull/6423#issuecomment-651209818 (We essentially built the PR to the TEST env and then tested across all browsers manually checking the cookie behaviour).

**Why was it reverted?**
The work was reverted because it broke our cypress tests on the TEST environment.

![image](https://user-images.githubusercontent.com/30599794/86239737-ca7f0800-bb97-11ea-8996-a7e6b97b923d.png)


**Suspicions to why it breaks on CI?**
When I ran the tests locally (install Cypress v3.4.1, and running `CYPRESS_APP_ENV=test CYPRESS_SMOKE=true npm run test:e2e:interactive`) the test would also fail. When I inspected the Cypress browser (electron), the cookies did not appear at all. I suspect this is because of this version of cypress incompatible with cookies that have a `sameSite` attribute as when I ran the test against a newer version of cypress it would pass.

_Note: The TEST env no longer has the cookie sameSite attribute so if you was to replicate this, it would pass._

**Next Steps?**
We should look into upgrading the cypress version we use on CI, as I suspect that to be the underlying issue.
Related issue: https://github.com/bbc/simorgh/issues/7075

Small PR where we tried to bump Cypress: https://github.com/bbc/simorgh/pull/6836#issuecomment-642817703

**Comment by chris-hinds** [comment]
Last time this issue was looked at we were blocked from merging it as an e2e test was failing (due to use using an older version of cypress).

We should look to either update or remove this specific test to unblock this work.

**Comment by karinathomasbbc** [comment]
We have decided to wait until we have CodePipeline running, as this will use the latest version of Cypress. We would rather invest time in the pipeline than trying to make this work with an old version of Cypress
